[project]
name = "m-gsm-symbolic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth Enevoldsen", email = "kennethcenevoldsen@gmail.com" },
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.82.0",
    "protobuf>=6.31.0",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ruff>=0.9.7", "ipykernel>=6.29.5", "pytest>=8.3.5"]
