[project]
name = "m-gsm-symbolic"
version = "0.1.0"
description = "A codebase for examining the cross-lingual transfer of reasoning."
readme = "README.md"
authors = [
    { name = "Kenneth Enevoldsen", email = "kennethcenevoldsen@gmail.com" },
    { name = "Nicolas Legrand", email = "nicolas.legrand@cas.au.dk" },
    { name = "Simon Enni", email = "enni@cas.au.dk" },
    { name = "Sofie Mosegaard", email = "sofie.mosegaard@cas.au.dk" },
]

requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
    "wandb>=0.19.11",
    "ipykernel>=6.29.5",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "unsloth>=2025.6.2",
    "vllm>=0.9.1",
    "bitsandbytes>=0.46.0",
    "triton>=3.3.0",
    "xformers>0.0.27",
    "trl>=0.18.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ruff>=0.9.7", "ipykernel>=6.29.5", "pytest>=8.3.5"]

[tool.uv.sources]
pydantic-ai = { git = "https://github.com/pydantic/pydantic-ai.git" } # TODO: Currenly required for https://github.com/pydantic/pydantic-ai/pulls?q=is%3Apr+include_expected_output+is%3Aclosed
