[project]
name = "m-gsm-symbolic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth Enevoldsen", email = "kennethcenevoldsen@gmail.com" },
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ruff>=0.9.7", "ipykernel>=6.29.5", "pytest>=8.3.5"]
