replacements = {
    "names": [
        "Sophie",
        "Andrea",
        "Abby",
        "Emma",
        "Claire",
        "Anna",
        "Ashley",
        "Laura",
        "Lily",
        "Ava",
        "Emily",
        "Olivia",
        "Madison",
        "Ella",
        "Maya",
        "Jessica",
        "Amanda",
        "Sophia",
        "Sarah",
        "Ellen",
        "Isabella",
        "Chris",
        "Oliver",
        "Noah",
        "Eric",
        "Jason",
        "Carl",
        "William",
        "Tyler",
        "Lucas",
        "Alex",
        "Joshua",
        "Ethan",
        "Michael",
        "Kenneth",
        "Matt",
        "Henry",
        "Joe",
        "Bob",
        "David",
    ],
    "names_female": [
        "Sophie",
        "Andrea",
        "Abby",
        "Emma",
        "Claire",
        "Anna",
        "Ashley",
        "Laura",
        "Lily",
        "Ava",
        "Emily",
        "Olivia",
        "Madison",
        "Ella",
        "Maya",
        "Jessica",
        "Amanda",
        "Sophia",
        "Sarah",
        "Ellen",
        "Isabella",
    ],
    "names_male": [
        "Chris",
        "Oliver",
        "Noah",
        "Eric",
        "Jason",
        "Carl",
        "William",
        "Tyler",
        "Lucas",
        "Alex",
        "Joshua",
        "Ethan",
        "Michael",
        "Kenneth",
        "Matt",
        "Henry",
        "Joe",
        "Bob",
        "David",
    ],
    "male_names": [
        "Chris",
        "Oliver",
        "Noah",
        "Eric",
        "Jason",
        "Carl",
        "William",
        "Tyler",
        "Lucas",
        "Alex",
        "Joshua",
        "Ethan",
        "Michael",
        "Kenneth",
        "Matt",
        "Henry",
        "Joe",
        "Bob",
        "David",
    ],
    "sports": [
        "football",
        "handball",
        "basketball",
        "tennis",
        "badminton",
        "swimming",
        "skating",
        "cycling",
        "running",
        "golf",
    ],
    "fruits": [
        "apple",
        "banana",
        "orange",
        "pear",
        "kiwi",
        "grapes",
        "strawberry",
        "blueberry",
        "raspberry",
        "melon",
    ],
    "colors": [
        "red",
        "green",
        "blue",
        "yellow",
        "orange",
        "purple",
        "pink",
        "brown",
        "black",
        "white",
    ],
    "cities": [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia",
        "San Antonio",
        "San Diego",
        "Dallas",
    ],
    "weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "months": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ],
    "weights_med": ["pound", "pounds", "lb", "ounce", "oz"],
    "weights_sm": ["pound", "pounds", "lb", "ounce", "oz"],
    "currencies_sym": ["dollars", "$"],
    "length_lg": ["ft", "feet", "yard", "mile", "mi"],
    "multiple_ice": ["twice", "thrice"],
    "multiple": [1, 2, 3],
    "multi_times": [2, 3],
    "fraction_nums": [1 / 2, 1 / 3, 1 / 4, 1 / 5],
    "fractions": [1 / 2, 1 / 3, 1 / 4, 1 / 5],
    "fraction_decimals": [0.5, 0.25, 0.75],
    "numbers": ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
}
