replacements = {
    "names": [
        "Sofie",
        "Andrea",
        "Freja",
        "Ida",
        "Clara",
        "Anna",
        "Astrid",
        "Laura",
        "Frida",
        "Alma",
        "Emma",
        "Olivia",
        "Agnes",
        "Ella",
        "Maja",
        "Esther",
        "Alberte",
        "Mathilde",
        "Signe",
        "Ellen",
        "Ingrid",
        "Christian",
        "Ole",
        "Niels",
        "Erik",
        "Kasper",
        "Carl",
        "William",
        "Tobias",
        "Lucas",
        "Alfred",
        "Asbjørn",
        "Emil",
        "Magnus",
        "Kenneth",
        "Mikkel",
        "Henrik",
        "Lars",
        "Bo",
        "Simon",
    ],
    "names_female": [
        "Sofie",
        "Andrea",
        "Freja",
        "Ida",
        "Clara",
        "Anna",
        "Astrid",
        "Laura",
        "Frida",
        "Alma",
        "Emma",
        "Olivia",
        "Agnes",
        "Ella",
        "Maja",
        "Esther",
        "Alberte",
        "Mathilde",
        "Signe",
        "Ellen",
        "Ingrid",
    ],
    "names_male": [
        "Christian",
        "Ole",
        "Niels",
        "Erik",
        "Kasper",
        "Carl",
        "William",
        "Tobias",
        "Lucas",
        "Alfred",
        "Asbjørn",
        "Emil",
        "Magnus",
        "Kenneth",
        "Mikkel",
        "Henrik",
        "Lars",
        "Bo",
        "Simon",
    ],
    "male_names": [
        "Christian",
        "Ole",
        "Niels",
        "Erik",
        "Kasper",
        "Carl",
        "William",
        "Tobias",
        "Lucas",
        "Alfred",
        "Asbjørn",
        "Emil",
        "Magnus",
        "Kenneth",
        "Mikkel",
        "Henrik",
        "Lars",
        "Bo",
        "Simon",
    ],
    "sports": [
        "fodbold",
        "håndbold",
        "basketball",
        "tennis",
        "badminton",
        "svømning",
        "skøjteløb",
        "cykling",
        "løb",
        "golf",
    ],
    "fruits": [
        "æble",
        "banan",
        "appelsin",
        "pære",
        "kiwi",
        "vindruer",
        "jordbær",
        "blåbær",
        "hindbær",
        "melon",
    ],
    "colors": [
        "rød",
        "grøn",
        "blå",
        "gul",
        "orange",
        "lilla",
        "pink",
        "brun",
        "sort",
        "hvid",
    ],
    "cities": [
        "København",
        "Aarhus",
        "Odense",
        "Aalborg",
        "Esbjerg",
        "Randers",
        "Kolding",
        "Horsens",
        "Vejle",
    ],
    "weekdays": ["mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lørdag", "søndag"],
    "months": [
        "januar",
        "februar",
        "marts",
        "april",
        "maj",
        "juni",
        "juli",
        "august",
        "september",
        "oktober",
        "november",
        "december",
    ],
    "weights_med": ["kilo", "kilogram", "kg", "gram", "g"],
    "weights_sm": ["kilo", "kilogram", "kg", "gram", "g"],
    "currencies_sym": ["kroner", "kr"],
    "length_lg": ["m", "meter", "km", "kilometer"],
    "multiple_ice": ["to gange", "tre gange"],
    "multiple": [1, 2, 3],
    "multi_times": [2, 3],
    "fraction_nums": [1 / 2, 1 / 3, 1 / 4, 1 / 5],
    "fractions": [1 / 2, 1 / 3, 1 / 4, 1 / 5],
    "fraction_decimals": [0.5, 0.25, 0.75],
    "numbers": ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
}
